<#
.SYNOPSIS
    Windsurf VM Manager - spin up, manage, and snapshot Windsurf IDE VMs on Windows.

.DESCRIPTION
    Wraps Vagrant + VirtualBox to provide a simple CLI for isolated Windsurf IDE
    development environments. Each instance gets its own VM, RDP port, snapshot
    history, and one-or-many shared project folders. Single-project VMs mount
    $ProjectPath at /project (legacy); multi-project VMs mount each selected
    project at /projects/<name>. See USAGE.md for all scenarios.

.USAGE
    vm new <name> [-p spec]     Create a VM (spec = comma-separated aliases/paths)
    vm start <name>             Start VM + open Remote Desktop
    vm stop <name>              Halt VM (state preserved)
    vm list                     List all instances with status + projects
    vm delete <name>            Permanently destroy a VM

    vm snapshot <name> <label>  Save a named snapshot
    vm restore <name> <label>   Restore VM to a snapshot
    vm snapshots <name>         List snapshots for an instance

    vm setup-host               One-time SSH bridge setup (auto-elevates)
    vm ssh <name>               SSH into VM from host terminal
    vm status <name>            Show connectivity + bridge health

.EXAMPLE
    vm new dev-main                           # single project (legacy)
    vm new dev-main -p mkt-tools,windsurf-vms # multi-project from aliases
    vm start dev-main
    vm snapshot dev-main clean-state
    vm restore dev-main clean-state
    vm stop dev-main
#>

param(
    [Parameter(Position=0)] [string] $Command     = "",
    [Parameter(Position=1)] [string] $Name        = "",
    [Parameter(Position=2)] [string] $Label       = "",
    # Project list for `vm new`. Comma-separated aliases from $Projects in
    # vm.config.ps1, and/or absolute Windows paths. See USAGE.md section 3.
    # NOTE: param name is ProjectSpec (not Projects) to avoid shadowing the
    # config hashtable when vm.config.ps1 is dot-sourced below.
    [Alias("p")]
    [string] $ProjectSpec = ""
)

# --- Load user config ---------------------------------------------------------
$RootDir      = $PSScriptRoot
$InstancesDir = Join-Path $RootDir "instances"
$RegistryFile = Join-Path $RootDir ".vm-registry.json"
$ConfigFile   = Join-Path $RootDir "vm.config.ps1"

# Defaults (overridden by vm.config.ps1 or first-run prompt)
$ProjectPath = ""
$Projects    = @{}   # alias -> host path (populated from config)
$VmRam       = 6144
$VmCpus      = 4
$VmDiskGB    = 40
$BaseRdpPort = 3390
$RdpWaitSec  = 8
$HostUser    = ""    # SSH bridge: Windows username (auto-detected if blank)

if (Test-Path $ConfigFile) {
    . $ConfigFile
}

# --- Bridge config (generated by setup-host-ssh.ps1) --------------------------
$BridgeConfigFile = Join-Path $RootDir ".bridge-config.json"
$BridgeSshDir     = Join-Path $RootDir ".ssh"
$BridgeEnabled    = $false
$BridgeConfig     = $null

if (Test-Path $BridgeConfigFile) {
    $BridgeConfig  = Get-Content $BridgeConfigFile -Raw | ConvertFrom-Json
    $BridgeEnabled = $true
    if ([string]::IsNullOrWhiteSpace($HostUser)) {
        $HostUser = $BridgeConfig.host_user
    }
}

# --- Tool resolution ---------------------------------------------------------
# VBoxManage and vagrant may not be on PATH. Search known install locations.
$script:VBoxManagePath = $null
$script:VagrantPath    = $null

function Resolve-VBoxManage {
    if ($script:VBoxManagePath) { return $script:VBoxManagePath }
    # Check PATH first
    $onPath = Get-Command VBoxManage -ErrorAction SilentlyContinue
    if ($onPath) { $script:VBoxManagePath = $onPath.Source; return $script:VBoxManagePath }
    # Known install locations
    foreach ($dir in @(
        "$env:ProgramFiles\Oracle\VirtualBox",
        "${env:ProgramFiles(x86)}\Oracle\VirtualBox",
        "$env:ProgramW6432\Oracle\VirtualBox"
    )) {
        $exe = Join-Path $dir "VBoxManage.exe"
        if (Test-Path $exe) { $script:VBoxManagePath = $exe; return $exe }
    }
    return $null
}

function Resolve-Vagrant {
    if ($script:VagrantPath) { return $script:VagrantPath }
    $onPath = Get-Command vagrant -ErrorAction SilentlyContinue
    if ($onPath) { $script:VagrantPath = $onPath.Source; return $script:VagrantPath }
    foreach ($dir in @(
        "$env:ProgramFiles\Vagrant\bin",
        "$env:SystemDrive\HashiCorp\Vagrant\bin"
    )) {
        $exe = Join-Path $dir "vagrant.exe"
        if (Test-Path $exe) { $script:VagrantPath = $exe; return $exe }
    }
    return $null
}

function Assert-Prerequisites {
    $vbox = Resolve-VBoxManage
    if (-not $vbox) {
        Write-Err "VBoxManage not found. Install VirtualBox or add it to PATH."
        Write-Info "Download: https://www.virtualbox.org/wiki/Downloads"
        exit 1
    }
    $vag = Resolve-Vagrant
    if (-not $vag) {
        Write-Err "Vagrant not found. Install Vagrant or add it to PATH."
        Write-Info "Download: https://developer.hashicorp.com/vagrant/downloads"
        exit 1
    }
}

# --- Helpers -----------------------------------------------------------------
function Write-Info  ($msg) { Write-Host "  $msg" -ForegroundColor Cyan }
function Write-Ok    ($msg) { Write-Host "  OK $msg" -ForegroundColor Green }
function Write-Warn  ($msg) { Write-Host "  ! $msg" -ForegroundColor Yellow }
function Write-Err   ($msg) { Write-Host "  X $msg" -ForegroundColor Red }

function Get-Registry {
    if (Test-Path $RegistryFile) {
        $raw = Get-Content $RegistryFile -Raw | ConvertFrom-Json
        return $raw
    }
    return [PSCustomObject]@{ instances = [PSCustomObject]@{} }
}

function Save-Registry ($reg) {
    # Atomic write: serialize -> tmp file -> atomic rename. Prevents a partial
    # JSON file if vm.ps1 is Ctrl+C'd mid-write. Move-Item -Force on NTFS
    # (same volume) uses MoveFileEx with MOVEFILE_REPLACE_EXISTING, which is
    # atomic. Works on Windows PowerShell 5.1 (.NET Framework 4.x) where the
    # 3-arg File.Move(src, dst, overwrite) overload is unavailable.
    $tmp = "$RegistryFile.tmp"
    $json = $reg | ConvertTo-Json -Depth 10
    [System.IO.File]::WriteAllText($tmp, $json, [System.Text.UTF8Encoding]::new($false))
    Move-Item -Path $tmp -Destination $RegistryFile -Force
}

function Test-InstanceName ($name) {
    # Reject names that are not safe for filesystem paths or VBox VM names.
    if ($name -notmatch '^[a-zA-Z0-9][a-zA-Z0-9_-]{0,31}$') {
        Write-Err "Invalid instance name '$name'."
        Write-Info "Allowed: 1-32 chars, start with alphanumeric, then [a-zA-Z0-9_-]."
        return $false
    }
    # Check collision with any existing VirtualBox VM on the host.
    $vboxName = "windsurf-$name"
    $vbm = Resolve-VBoxManage
    $existing = ""
    if ($vbm) {
        try { $existing = & $vbm list vms 2>$null | Out-String } catch {}
    }
    if ($existing -match [regex]::Escape("`"$vboxName`"")) {
        # Collision is OK only if it's our own registry entry (re-use / resume).
        $reg = Get-Registry
        if (-not (Get-Instance $reg $name)) {
            Write-Err "A VirtualBox VM named '$vboxName' already exists but is not tracked by this tool."
            Write-Info "Pick a different name, or remove it with: VBoxManage unregistervm '$vboxName' --delete"
            return $false
        }
    }
    return $true
}

function Test-PortInUse ($port) {
    # True if another process on the host is listening on $port.
    try {
        $conn = Get-NetTCPConnection -LocalPort $port -ErrorAction SilentlyContinue
        return ($null -ne $conn)
    } catch {
        return $false
    }
}

function Get-VBoxRunningVMs {
    # Returns a hashtable: vm_name -> $true for every currently running VBox VM.
    $result = @{}
    try {
        $vbm = Resolve-VBoxManage
        if (-not $vbm) { return $result }
        $output = & $vbm list runningvms 2>$null | Out-String
        foreach ($line in $output -split "`r?`n") {
            if ($line -match '^"([^"]+)"') { $result[$Matches[1]] = $true }
        }
    } catch {
        # VBoxManage not on PATH — registry status will be shown as-is.
    }
    return $result
}

function Resolve-Projects ($spec, $aliases) {
    # Parse a comma-separated spec like "mkt-tools,C:\Temp\issue-123".
    # Returns a PSCustomObject { Success; Projects; Error }:
    #   Success=$true,  Projects=@()            -> legacy single-mount mode
    #   Success=$true,  Projects=@(...)         -> multi-project mode
    #   Success=$false, Error="..."             -> caller should exit 1
    $emptyResult = [PSCustomObject]@{ Success = $true; Projects = @(); Error = "" }
    if ([string]::IsNullOrWhiteSpace($spec)) { return $emptyResult }

    $tokens = $spec -split ',' | ForEach-Object { $_.Trim() } | Where-Object { $_ }
    $resolved  = New-Object System.Collections.ArrayList
    $seenNames = @{}

    foreach ($token in $tokens) {
        $mountName = ""
        $hostPath  = ""

        if ($aliases -and $aliases.ContainsKey($token)) {
            $mountName = $token
            $hostPath  = $aliases[$token]
        }
        elseif ($token -match '^[A-Za-z]:[\\/]' -or $token -match '^\\\\') {
            $hostPath  = $token
            $leaf      = Split-Path -Leaf $token
            # Sanitize: lowercase, non-[a-z0-9] runs -> '-', trim leading/trailing '-'
            $mountName = ($leaf.ToLower() -replace '[^a-z0-9]+', '-').Trim('-')
            if ([string]::IsNullOrWhiteSpace($mountName)) {
                return [PSCustomObject]@{
                    Success = $false
                    Projects = @()
                    Error = "Cannot derive a valid mount name from path: '$token' (Hint: add an alias in `$Projects with an ASCII name)"
                }
            }
        }
        else {
            $availList = if ($aliases -and $aliases.Count -gt 0) { ($aliases.Keys | Sort-Object) -join ', ' } else { '(none)' }
            return [PSCustomObject]@{
                Success = $false
                Projects = @()
                Error = "Unknown project alias or invalid path: '$token'`n  Available aliases: $availList`n  (Hint: use an alias or an absolute Windows path like C:\foo)"
            }
        }

        if ($seenNames.ContainsKey($mountName)) {
            return [PSCustomObject]@{
                Success = $false
                Projects = @()
                Error = "Duplicate project name: '$mountName' (from '$($seenNames[$mountName])' and '$hostPath')`n  (Hint: add one as an alias in `$Projects with a unique name)"
            }
        }
        $seenNames[$mountName] = $hostPath

        if (-not (Test-Path -LiteralPath $hostPath)) {
            Write-Warn "Host path does not exist: $hostPath"
            $confirm = Read-Host "  Continue anyway? (y/N)"
            if ($confirm -ne 'y') {
                return [PSCustomObject]@{
                    Success = $false
                    Projects = @()
                    Error = "Aborted by user (missing host path)"
                }
            }
        }

        [void]$resolved.Add([PSCustomObject]@{ name = $mountName; host_path = $hostPath })
    }

    return [PSCustomObject]@{
        Success  = $true
        Projects = @($resolved.ToArray())
        Error    = ""
    }
}

function Prompt-Projects ($instanceName, $aliases) {
    # Interactive prompt when `vm new` is invoked without -p.
    Write-Host ""
    Write-Host "  Projects to mount for '$instanceName':" -ForegroundColor Cyan
    $list = if ($aliases -and $aliases.Count -gt 0) {
        ($aliases.Keys | Sort-Object) -join ', '
    } else { '(none defined in config)' }
    Write-Host "    Available aliases: $list" -ForegroundColor Gray
    Write-Host "    (comma-separated aliases or absolute paths; empty = legacy `$ProjectPath)" -ForegroundColor Gray
    return (Read-Host "  Select")
}

function Get-InstanceProjects ($instance) {
    # Returns an array of project objects for an instance, or @() if the
    # instance is in legacy single-mount mode (no `projects` field in registry).
    if ($instance -and $instance.PSObject.Properties["projects"]) {
        $p = $instance.projects
        if ($null -ne $p) { return @($p) }
    }
    return @()
}

function Format-ProjectSummary ($instance) {
    $projects = Get-InstanceProjects $instance
    if ($projects.Count -gt 0) {
        return (($projects | ForEach-Object { $_.name }) -join ', ')
    }
    if ($instance -and $instance.PSObject.Properties["host_only_ip"]) {
        return "Windows home (Remote-SSH)"
    }
    return "/project (legacy)"
}

function Get-NextPort ($reg) {
    $used = @()
    foreach ($prop in $reg.instances.PSObject.Properties) {
        $used += $prop.Value.rdp_port
    }
    $port = $BaseRdpPort
    # Skip ports already taken by another VM in our registry OR already bound
    # by any other process on the host (tested via Get-NetTCPConnection).
    while (($port -in $used) -or (Test-PortInUse $port)) {
        $port++
    }
    return $port
}

function Get-NextHostOnlyIP ($reg) {
    # Allocate from 192.168.56.10 upward, skip IPs already in use by other VMs.
    $used = @()
    foreach ($prop in $reg.instances.PSObject.Properties) {
        if ($prop.Value.PSObject.Properties["host_only_ip"]) {
            $used += $prop.Value.host_only_ip
        }
    }
    for ($i = 10; $i -le 254; $i++) {
        $candidate = "192.168.56.$i"
        if ($candidate -notin $used) { return $candidate }
    }
    Write-Err "No available host-only IPs (all 192.168.56.10-254 allocated)"
    exit 1
}

function Get-Instance ($reg, $name) {
    if ($reg.instances.PSObject.Properties[$name]) {
        return $reg.instances.$name
    }
    return $null
}

function Get-VmBox {
    # Use pre-built windsurf-base box if available (fast, no provisioning needed)
    # Otherwise fall back to ubuntu/jammy64 + provision.sh (~15 min first time)
    $vag = Resolve-Vagrant
    if (-not $vag) { return "ubuntu/jammy64" }
    $boxes = & $vag box list 2>$null | Out-String
    if ($boxes -match "windsurf-base") {
        return "windsurf-base"
    }
    return "ubuntu/jammy64"
}

function Invoke-Vagrant ($instanceName, $rdpPort, [string[]]$vagrantArgs, $projects = $null) {
    $instanceDir = Join-Path $InstancesDir $instanceName
    New-Item -ItemType Directory -Force -Path $instanceDir | Out-Null

    # Resolve projects: explicit param -> registry lookup -> legacy (empty)
    if ($null -eq $projects) {
        $reg      = Get-Registry
        $instance = Get-Instance $reg $instanceName
        $projects = Get-InstanceProjects $instance
    }
    # Build JSON array manually: ConvertTo-Json on a 1-element array in PS 5.1
    # unwraps to a JSON object (not array), which would break the Vagrantfile
    # parser. Serialize each element independently and wrap in brackets.
    $projectsJson = if ($projects.Count -eq 0) {
        "[]"
    } else {
        $items = $projects | ForEach-Object { ConvertTo-Json -InputObject $_ -Compress }
        "[" + ($items -join ",") + "]"
    }

    $env:VM_INSTANCE_NAME    = $instanceName
    $env:VM_RDP_PORT         = "$rdpPort"
    $env:VM_PROJECT_PATH     = $ProjectPath
    $env:VM_PROJECTS         = $projectsJson
    $env:VM_RAM              = "$VmRam"
    $env:VM_CPUS             = "$VmCpus"
    $env:VM_DISK_GB          = "$VmDiskGB"
    $env:VM_BOX              = Get-VmBox
    $env:VAGRANT_DOTFILE_PATH = $instanceDir
    $env:VAGRANT_CWD         = $RootDir

    # SSH Bridge env vars (only set when bridge is configured)
    $reg2      = Get-Registry
    $inst2     = Get-Instance $reg2 $instanceName
    $hostOnlyIP = ""
    if ($inst2 -and $inst2.PSObject.Properties["host_only_ip"]) {
        $hostOnlyIP = $inst2.host_only_ip
    }
    $env:VM_HOST_ONLY_IP = $hostOnlyIP

    if ($BridgeEnabled -and $hostOnlyIP) {
        $bridgeKeyPath = Join-Path $BridgeSshDir "vm_bridge_key"
        $hostKeyPath   = Join-Path $BridgeSshDir "host_key"
        if (Test-Path $bridgeKeyPath) {
            $env:VM_HOST_IP    = $BridgeConfig.host_ip
            $env:VM_HOST_USER  = $HostUser
            $env:VM_BRIDGE_KEY = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($bridgeKeyPath))
            if (Test-Path $hostKeyPath) {
                $env:VM_HOST_KEY = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($hostKeyPath))
            }
        } else {
            Write-Warn "Bridge key not found at $bridgeKeyPath -- run 'vm setup-host' to fix."
        }
    }

    # Tee Vagrant output to both host stdout and a per-instance log so failures
    # can be inspected later without scrolling the terminal buffer.
    $logFile = Join-Path $instanceDir "last-run.log"
    try {
        $vag = Resolve-Vagrant
        if (-not $vag) { Write-Err "Vagrant not found."; return 1 }
        & $vag @vagrantArgs 2>&1 | Tee-Object -FilePath $logFile | Out-Host
        $code = $LASTEXITCODE
        return $code
    }
    finally {
        Remove-Item Env:VM_INSTANCE_NAME     -ErrorAction SilentlyContinue
        Remove-Item Env:VM_RDP_PORT          -ErrorAction SilentlyContinue
        Remove-Item Env:VM_PROJECT_PATH      -ErrorAction SilentlyContinue
        Remove-Item Env:VM_PROJECTS          -ErrorAction SilentlyContinue
        Remove-Item Env:VM_RAM               -ErrorAction SilentlyContinue
        Remove-Item Env:VM_CPUS              -ErrorAction SilentlyContinue
        Remove-Item Env:VM_DISK_GB           -ErrorAction SilentlyContinue
        Remove-Item Env:VM_BOX               -ErrorAction SilentlyContinue
        Remove-Item Env:VAGRANT_DOTFILE_PATH -ErrorAction SilentlyContinue
        Remove-Item Env:VAGRANT_CWD          -ErrorAction SilentlyContinue
        Remove-Item Env:VM_HOST_ONLY_IP      -ErrorAction SilentlyContinue
        Remove-Item Env:VM_HOST_IP           -ErrorAction SilentlyContinue
        Remove-Item Env:VM_HOST_USER         -ErrorAction SilentlyContinue
        Remove-Item Env:VM_BRIDGE_KEY        -ErrorAction SilentlyContinue
        Remove-Item Env:VM_HOST_KEY          -ErrorAction SilentlyContinue
    }
}

function Ensure-Config {
    # Bridge mode: Windsurf accesses host via Remote-SSH, so legacy ProjectPath
    # and first-time setup prompt are unnecessary. Only need VM resource settings.
    if ($BridgeEnabled -and -not (Test-Path $ConfigFile)) {
        $configContent  = "# Windsurf VM - User Configuration (auto-generated)`n"
        $configContent += "# Bridge mode active -- Windsurf accesses host via Remote-SSH.`n`n"
        $configContent += "`$ProjectPath = `"`"`n`n"
        $configContent += "# Named project aliases for 'vm new <name> -p alias1,alias2'.`n"
        $configContent += "# Optional: shared folders mount at /projects/<name> inside VM.`n"
        $configContent += "# Add entries like:  `"mkt-tools`" = `"C:\\Dev\\mkt-tools`"`n"
        $configContent += "`$Projects = @{}`n`n"
        $configContent += "`$VmRam       = $VmRam`n"
        $configContent += "`$VmCpus      = $VmCpus`n"
        $configContent += "`$VmDiskGB    = $VmDiskGB`n"
        $configContent += "`$BaseRdpPort = $BaseRdpPort`n"
        Set-Content $ConfigFile $configContent -Encoding UTF8
        Write-Ok "Config created (bridge mode - defaults applied)"
        return
    }

    if ($BridgeEnabled) { return }

    # Legacy mode: prompt for project path if no config exists
    if ([string]::IsNullOrWhiteSpace($ProjectPath)) {
        Write-Host ""
        Write-Host "  First-time setup" -ForegroundColor Cyan
        Write-Host "  ---------------------------------------------------------" -ForegroundColor DarkGray
        Write-Host "  No vm.config.ps1 found. Running first-time setup." -ForegroundColor Gray
        Write-Host ""

        $defaultPath = "$env:USERPROFILE\Desktop\my-project"
        $inputPath = Read-Host "  Project folder path (default: $defaultPath)"
        if ([string]::IsNullOrWhiteSpace($inputPath)) { $inputPath = $defaultPath }

        $inputRam = Read-Host "  RAM in MB [6144]"
        if ([string]::IsNullOrWhiteSpace($inputRam)) { $inputRam = "6144" }

        $inputCpus = Read-Host "  CPU cores [4]"
        if ([string]::IsNullOrWhiteSpace($inputCpus)) { $inputCpus = "4" }

        $inputDisk = Read-Host "  Disk size in GB [40]"
        if ([string]::IsNullOrWhiteSpace($inputDisk)) { $inputDisk = "40" }

        $inputPort = Read-Host "  Base RDP port [3390]"
        if ([string]::IsNullOrWhiteSpace($inputPort)) { $inputPort = "3390" }

        $configContent  = "# Windsurf VM - User Configuration (auto-generated)`n"
        $configContent += "# See vm.config.example.ps1 for all available options.`n`n"
        $configContent += "# Legacy single-project fallback (used when -p is omitted at 'vm new').`n"
        $configContent += "`$ProjectPath = `"$inputPath`"`n`n"
        $configContent += "# Named project aliases for 'vm new <name> -p alias1,alias2'.`n"
        $configContent += "# Add entries like:  `"mkt-tools`" = `"C:\\Dev\\mkt-tools`"`n"
        $configContent += "`$Projects = @{}`n`n"
        $configContent += "`$VmRam       = $inputRam`n"
        $configContent += "`$VmCpus      = $inputCpus`n"
        $configContent += "`$VmDiskGB    = $inputDisk`n"
        $configContent += "`$BaseRdpPort = $inputPort`n"
        Set-Content $ConfigFile $configContent -Encoding UTF8

        # Apply in current session
        $script:ProjectPath = $inputPath
        $script:VmRam       = [int]$inputRam
        $script:VmCpus      = [int]$inputCpus
        $script:VmDiskGB    = [int]$inputDisk
        $script:BaseRdpPort = [int]$inputPort

        Write-Host ""
        Write-Ok "Config saved to vm.config.ps1"
        Write-Host ""
    }

    # Validate project path exists (legacy mode only)
    if (-not [string]::IsNullOrWhiteSpace($ProjectPath) -and -not (Test-Path $ProjectPath)) {
        Write-Warn "Project path does not exist: $ProjectPath"
        Write-Info "Creating it..."
        New-Item -ItemType Directory -Force -Path $ProjectPath | Out-Null
    }
}

function Show-Help {
    Write-Host ""
    Write-Host "  Windsurf VM Manager" -ForegroundColor Cyan
    Write-Host "  ---------------------------------------------------------" -ForegroundColor DarkGray
    Write-Host "  vm new <name> [-p spec]     Create new VM (auto-provisions)"
    Write-Host "                              spec: comma-separated aliases or absolute paths"
    Write-Host "  vm start <name>             Start VM + open RDP"
    Write-Host "  vm stop <name>              Halt VM (state preserved)"
    Write-Host "  vm list                     List all instances + projects"
    Write-Host "  vm delete <name>            Destroy VM permanently"
    Write-Host ""
    Write-Host "  vm snapshot <name> <label>  Save VM snapshot"
    Write-Host "  vm restore <name> <label>   Restore to snapshot"
    Write-Host "  vm snapshots <name>         List snapshots"
    Write-Host ""
    Write-Host "  vm setup-host               One-time SSH bridge setup (auto-elevates)"
    Write-Host "  vm ssh <name>               SSH into VM from host"
    Write-Host "  vm status <name>            Show detailed connectivity info"
    Write-Host ""
    Write-Host "  Examples:" -ForegroundColor DarkGray
    Write-Host "    vm setup-host                               # one-time bridge setup"
    Write-Host "    vm new dev                                  # bridge: no -p needed"
    Write-Host "    vm new dev -p mkt-tools                     # optional: shared folders"
    Write-Host "    vm start dev                                # RDP + auto Remote-SSH"
    Write-Host "    vm ssh dev                                  # SSH into VM"
    Write-Host "    vm status dev                               # check bridge health"
    Write-Host ""
    Write-Host "  Full docs: USAGE.md / README.md" -ForegroundColor DarkGray
    Write-Host ""
}

function Assert-Name {
    if ([string]::IsNullOrWhiteSpace($Name)) {
        Write-Err "Instance name required. Usage: vm $Command <name>"
        exit 1
    }
}

function Assert-Label {
    if ([string]::IsNullOrWhiteSpace($Label)) {
        Write-Err "Snapshot label required. Usage: vm $Command $Name <label>"
        exit 1
    }
}

# --- Commands -----------------------------------------------------------------
switch ($Command.ToLower()) {

    "new" {
        Assert-Name
        Assert-Prerequisites
        if (-not (Test-InstanceName $Name)) { exit 1 }
        Ensure-Config

        $reg      = Get-Registry
        $existing = Get-Instance $reg $Name

        if ($existing) {
            if ($existing.status -in @("error", "provisioning")) {
                $resumeReason = if ($existing.status -eq "error") { "previously failed to provision" } else { "interrupted mid-provision" }
                Write-Warn "Instance '$Name' was $resumeReason. Resuming..."
                $exitCode = Invoke-Vagrant $Name $existing.rdp_port @("up", "--provision")
                $reg = Get-Registry
                $reg.instances.$Name.status = if ($exitCode -eq 0) { "ready" } else { "error" }
                Save-Registry $reg
                if ($exitCode -eq 0) {
                    Write-Ok "VM '$Name' resume succeeded."
                } else {
                    Write-Err "Resume failed (exit $exitCode). See instances/$Name/last-run.log"
                    exit 1
                }
                exit 0
            }
            Write-Warn "Instance '$Name' already exists (port $($existing.rdp_port))."
            Write-Info "Use 'vm start $Name' to launch it."
            exit 1
        }

        # Resolve project list: either from -p CLI flag or interactive prompt.
        # Bridge mode: skip prompt entirely when no -p (browse mode, no shared folders).
        $spec = if (-not [string]::IsNullOrWhiteSpace($ProjectSpec)) {
            $ProjectSpec
        } elseif ($BridgeEnabled) {
            ""   # bridge browse mode: no shared folders needed
        } else {
            Prompt-Projects $Name $Projects
        }
        $resolution = Resolve-Projects $spec $Projects
        if (-not $resolution.Success) {
            Write-Err $resolution.Error
            exit 1
        }
        $projectsArr = @($resolution.Projects)

        $port  = Get-NextPort $reg
        $box   = Get-VmBox
        $isNew = $box -eq "ubuntu/jammy64"

        # Allocate host-only IP when bridge is configured
        $vmHostOnlyIP = ""
        if ($BridgeEnabled) {
            $vmHostOnlyIP = Get-NextHostOnlyIP $reg
        }

        Write-Host ""
        Write-Host "  Creating VM '$Name'" -ForegroundColor Cyan
        Write-Host "  RDP port : localhost:$port"
        if ($vmHostOnlyIP) {
            Write-Host "  Bridge   : $vmHostOnlyIP -> host ($($BridgeConfig.host_ip))"
        }
        if ($projectsArr.Count -eq 0 -and $vmHostOnlyIP) {
            Write-Host "  Projects : (bridge browse mode - no shared folders)"
        } elseif ($projectsArr.Count -eq 0) {
            Write-Host "  Projects : (legacy) $ProjectPath -> /project"
        } else {
            Write-Host "  Projects :"
            foreach ($p in $projectsArr) {
                Write-Host ("               {0,-16} -> {1,-40} -> /projects/{0}" -f $p.name, $p.host_path)
            }
        }
        Write-Host "  RAM      : $([math]::Round($VmRam/1024, 0)) GB  |  CPU: $VmCpus cores  |  Disk: $VmDiskGB GB"
        Write-Host "  Box      : $box"
        Write-Host ""
        if ($isNew) {
            Write-Warn "First run: downloads Ubuntu box (~700 MB) + provisions (~15 min)."
        } else {
            Write-Info "Using pre-built windsurf-base box - VM ready in ~1-2 min."
        }
        Write-Host ""

        # Registry entry: only include `projects` field when multi-project. VMs
        # without the field are treated as legacy by Get-InstanceProjects.
        $newEntry = [PSCustomObject]@{
            rdp_port = $port
            created  = (Get-Date).ToString("yyyy-MM-dd HH:mm")
            status   = "provisioning"
        }
        if ($projectsArr.Count -gt 0) {
            $newEntry | Add-Member -NotePropertyName "projects" -NotePropertyValue $projectsArr
        }
        if ($vmHostOnlyIP) {
            $newEntry | Add-Member -NotePropertyName "host_only_ip" -NotePropertyValue $vmHostOnlyIP
        }
        $reg.instances | Add-Member -NotePropertyName $Name -NotePropertyValue $newEntry
        Save-Registry $reg

        $exitCode = Invoke-Vagrant $Name $port @("up") $projectsArr

        if ($exitCode -eq 0) {
            $reg = Get-Registry
            $reg.instances.$Name.status = "ready"
            Save-Registry $reg

            Write-Host ""
            Write-Ok "VM '$Name' is ready!"
            Write-Host "  Run: vm start $Name" -ForegroundColor Gray
        } else {
            Write-Err "Provisioning failed (exit $exitCode). Check output above."
            $reg = Get-Registry
            $reg.instances.$Name.status = "error"
            Save-Registry $reg
            exit 1
        }
    }

    "start" {
        Assert-Name
        Assert-Prerequisites
        Ensure-Config

        $reg      = Get-Registry
        $instance = Get-Instance $reg $Name

        if (-not $instance) {
            Write-Err "Instance '$Name' not found."
            Write-Info "Use 'vm new $Name' to create it, or 'vm list' to see all instances."
            exit 1
        }

        $port = $instance.rdp_port
        Write-Host ""
        Write-Info "Starting VM '$Name' (RDP: localhost:$port)..."

        $exitCode = Invoke-Vagrant $Name $port @("up")

        if ($exitCode -ne 0) {
            Write-Err "Failed to start VM (exit $exitCode)."
            exit 1
        }

        Write-Info "Waiting $RdpWaitSec s for RDP service..."
        Start-Sleep $RdpWaitSec

        Write-Info "Opening Remote Desktop..."
        Start-Process "mstsc" "/v:localhost:$port"

        $reg = Get-Registry
        $reg.instances.$Name.status = "running"
        Save-Registry $reg

        $projSummary = Format-ProjectSummary $instance
        $hasBridge = $instance.PSObject.Properties["host_only_ip"]
        $projLabel = if ((Get-InstanceProjects $instance).Count -eq 0 -and $hasBridge) {
            "(browse mode - no shared folders)"
        } elseif ((Get-InstanceProjects $instance).Count -eq 0) {
            "/project  (shared folder)"
        } else {
            "$projSummary  (mounted under /projects/)"
        }

        # Bridge status
        $bridgeLabel = ""
        if ($instance.PSObject.Properties["host_only_ip"]) {
            $hostIpDisplay = if ($BridgeConfig) { $BridgeConfig.host_ip } else { "192.168.56.1" }
            $bridgeLabel = "Remote-SSH auto-connects to host ($($instance.host_only_ip) -> $hostIpDisplay)"
        }

        Write-Host ""
        Write-Ok "Connected to '$Name'"
        Write-Host "  Login    : vagrant / vagrant" -ForegroundColor Gray
        Write-Host "  Projects : $projLabel" -ForegroundColor Gray
        if ($bridgeLabel) {
            Write-Host "  Bridge   : $bridgeLabel" -ForegroundColor Gray
            $winHome = if ($HostUser) { "C:\Users\$HostUser" } else { "Windows home" }
            Write-Host "  Windsurf : auto-opens $winHome via Remote-SSH" -ForegroundColor Gray
        } else {
            Write-Host "  Windsurf : launches from application menu" -ForegroundColor Gray
        }
        Write-Host ""
    }

    "stop" {
        Assert-Name
        Assert-Prerequisites
        $reg      = Get-Registry
        $instance = Get-Instance $reg $Name

        if (-not $instance) {
            Write-Err "Instance '$Name' not found."
            exit 1
        }

        Write-Info "Stopping VM '$Name'..."
        $exitCode = Invoke-Vagrant $Name $instance.rdp_port @("halt")

        $reg = Get-Registry
        if ($exitCode -eq 0) {
            $reg.instances.$Name.status = "stopped"
            Save-Registry $reg
            Write-Ok "VM '$Name' stopped. State preserved - 'vm start $Name' to resume."
        } else {
            Write-Warn "vagrant halt returned error (exit $exitCode). VM may still be running."
            Write-Info "Check status: vm list"
        }
    }

    "list" {
        $reg = Get-Registry
        Write-Host ""
        Write-Host "  Windsurf VM Instances" -ForegroundColor Cyan
        Write-Host "  ---------------------------------------------------------" -ForegroundColor DarkGray

        $props = $reg.instances.PSObject.Properties
        if ($props.Count -eq 0) {
            Write-Host "  (no instances)  Use: vm new <name>" -ForegroundColor DarkGray
        } else {
            # Reconcile registry state against actual VirtualBox state so that
            # externally-halted VMs aren't shown as 'running'.
            $running   = Get-VBoxRunningVMs
            $regDirty  = $false
            foreach ($prop in $props) {
                $inst   = $prop.Value
                $vboxName = "windsurf-$($prop.Name)"
                $actual = if ($running.ContainsKey($vboxName)) { "running" } else { $inst.status }
                # Drift detection: registry says running, VBox says not.
                if ($inst.status -eq "running" -and -not $running.ContainsKey($vboxName)) {
                    $inst.status = "stopped"
                    $actual = "stopped"
                    $regDirty = $true
                }
                $status = $actual
                $color  = switch ($status) {
                    "running"      { "Green" }
                    "ready"        { "Yellow" }
                    "stopped"      { "DarkGray" }
                    "provisioning" { "Cyan" }
                    "error"        { "Red" }
                    default        { "Gray" }
                }
                $sshInfo = ""
                if ($inst.PSObject.Properties["host_only_ip"]) {
                    $sshInfo = "  SSH: $($inst.host_only_ip)"
                }
                $line = "  {0,-12} RDP: localhost:{1,-5}{2}  [{3}]  Created: {4}" -f `
                    $prop.Name, $inst.rdp_port, $sshInfo, $status, $inst.created
                Write-Host $line -ForegroundColor $color
                $projLine = "               Projects: {0}" -f (Format-ProjectSummary $inst)
                Write-Host $projLine -ForegroundColor DarkGray
                if ($inst.PSObject.Properties["host_only_ip"] -and $status -eq "running") {
                    Write-Host "               Bridge: auto-connected to host" -ForegroundColor DarkGray
                }
            }
            if ($regDirty) { Save-Registry $reg }
        }

        Write-Host "  ---------------------------------------------------------" -ForegroundColor DarkGray
        Write-Host ""
    }

    "delete" {
        Assert-Name
        Assert-Prerequisites
        $reg      = Get-Registry
        $instance = Get-Instance $reg $Name

        if (-not $instance) {
            Write-Err "Instance '$Name' not found."
            exit 1
        }

        Write-Host ""
        Write-Warn "This will PERMANENTLY destroy VM '$Name' and all its snapshots."
        Write-Host "  (Your project files are NOT affected)" -ForegroundColor DarkGray
        $confirm = Read-Host "  Type 'yes' to confirm"

        if ($confirm -ne "yes") {
            Write-Info "Cancelled."
            exit 0
        }

        Write-Info "Destroying VM '$Name'..."
        Invoke-Vagrant $Name $instance.rdp_port @("destroy", "-f") | Out-Null

        $newInstances = [PSCustomObject]@{}
        foreach ($prop in $reg.instances.PSObject.Properties) {
            if ($prop.Name -ne $Name) {
                $newInstances | Add-Member -NotePropertyName $prop.Name -NotePropertyValue $prop.Value
            }
        }
        $reg.instances = $newInstances
        Save-Registry $reg

        $instanceDir = Join-Path $InstancesDir $Name
        Remove-Item -Recurse -Force $instanceDir -ErrorAction SilentlyContinue

        Write-Ok "VM '$Name' deleted."
    }

    "snapshot" {
        Assert-Name
        Assert-Label
        Assert-Prerequisites
        $reg      = Get-Registry
        $instance = Get-Instance $reg $Name

        if (-not $instance) {
            Write-Err "Instance '$Name' not found."
            exit 1
        }

        Write-Info "Saving snapshot '$Label' for '$Name'..."
        Invoke-Vagrant $Name $instance.rdp_port @("snapshot", "save", "--force", $Label)
        Write-Ok "Snapshot '$Label' saved."
    }

    "restore" {
        Assert-Name
        Assert-Label
        Assert-Prerequisites
        $reg      = Get-Registry
        $instance = Get-Instance $reg $Name

        if (-not $instance) {
            Write-Err "Instance '$Name' not found."
            exit 1
        }

        Write-Warn "This will revert '$Name' to snapshot '$Label'. Unsaved VM state will be lost."
        $confirm = Read-Host "  Confirm? (y/N)"
        if ($confirm -ne "y") { Write-Info "Cancelled."; exit 0 }

        Write-Info "Restoring '$Name' to '$Label'..."
        Invoke-Vagrant $Name $instance.rdp_port @("snapshot", "restore", $Label)
        Write-Ok "'$Name' restored to '$Label'."
    }

    "snapshots" {
        Assert-Name
        Assert-Prerequisites
        $reg      = Get-Registry
        $instance = Get-Instance $reg $Name

        if (-not $instance) {
            Write-Err "Instance '$Name' not found."
            exit 1
        }

        Write-Info "Snapshots for '$Name':"
        Invoke-Vagrant $Name $instance.rdp_port @("snapshot", "list")
    }

    "setup-host" {
        Write-Info "Running host SSH bridge setup..."
        $setupScript = Join-Path $RootDir "setup-host-ssh.ps1"
        if (-not (Test-Path $setupScript)) {
            Write-Err "setup-host-ssh.ps1 not found in $RootDir"
            exit 1
        }
        & powershell -NoProfile -ExecutionPolicy Bypass -File $setupScript
        $code = $LASTEXITCODE
        if ($code -ne 0) { exit $code }
    }

    "ssh" {
        Assert-Name
        Assert-Prerequisites
        $reg      = Get-Registry
        $instance = Get-Instance $reg $Name

        if (-not $instance) {
            Write-Err "Instance '$Name' not found."
            exit 1
        }

        # Use vagrant ssh — handles port (incl. auto_correct) and keys automatically.
        $instanceDir = Join-Path $InstancesDir $Name
        $vag = Resolve-Vagrant
        $env:VAGRANT_DOTFILE_PATH = $instanceDir
        $env:VAGRANT_CWD          = $RootDir
        try {
            Write-Info "SSH into '$Name' (via vagrant ssh)..."
            & $vag ssh
            exit $LASTEXITCODE
        } finally {
            Remove-Item Env:VAGRANT_DOTFILE_PATH -ErrorAction SilentlyContinue
            Remove-Item Env:VAGRANT_CWD          -ErrorAction SilentlyContinue
        }
    }

    "status" {
        Assert-Name
        $reg      = Get-Registry
        $instance = Get-Instance $reg $Name

        if (-not $instance) {
            Write-Err "Instance '$Name' not found."
            exit 1
        }

        Write-Host ""
        Write-Host "  VM Status: $Name" -ForegroundColor Cyan
        Write-Host "  ---------------------------------------------------------" -ForegroundColor DarkGray
        Write-Host "  RDP        : localhost:$($instance.rdp_port)"
        Write-Host "  Status     : $($instance.status)"
        Write-Host "  Created    : $($instance.created)"
        Write-Host "  Projects   : $(Format-ProjectSummary $instance)"

        if ($instance.PSObject.Properties["host_only_ip"]) {
            $ip = $instance.host_only_ip
            $hostIp = if ($BridgeConfig) { $BridgeConfig.host_ip } else { "192.168.56.1" }
            Write-Host "  Host-only  : $ip"
            Write-Host "  Bridge to  : $hostIp (user: $HostUser)" 

            # Test SSH connectivity (both directions) if VM appears to be running
            $running2  = Get-VBoxRunningVMs
            $vboxName2 = "windsurf-$Name"
            if ($running2.ContainsKey($vboxName2)) {
                $instanceDir2 = Join-Path $InstancesDir $Name
                $vag2 = Resolve-Vagrant
                if ($vag2) {
                    $env:VAGRANT_DOTFILE_PATH = $instanceDir2
                    $env:VAGRANT_CWD          = $RootDir
                    try {
                        # Test 1: host → VM
                        $vmTest = & $vag2 ssh -c "echo vm_ok" 2>&1 | Out-String
                        Write-Host "  SSH host→VM  : " -NoNewline
                        if ($vmTest -match "vm_ok") {
                            Write-Host "OK" -ForegroundColor Green
                            # Test 2: VM → host (bridge) -- only when bridge configured
                            $bridgeTest = & $vag2 ssh -c `
                                "ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new host echo bridge_ok 2>&1" `
                                2>&1 | Out-String
                            Write-Host "  SSH VM→host  : " -NoNewline
                            if ($bridgeTest -match "bridge_ok") {
                                Write-Host "OK  (bridge working)" -ForegroundColor Green
                            } else {
                                Write-Host "FAILED  (run: vm setup-host)" -ForegroundColor Red
                            }
                        } else {
                            Write-Host "FAILED" -ForegroundColor Red
                        }
                    } finally {
                        Remove-Item Env:VAGRANT_DOTFILE_PATH -ErrorAction SilentlyContinue
                        Remove-Item Env:VAGRANT_CWD          -ErrorAction SilentlyContinue
                    }
                }
            }
        } else {
            Write-Host "  Bridge     : not configured"
        }

        Write-Host "  ---------------------------------------------------------" -ForegroundColor DarkGray
        Write-Host ""
    }

    { $_ -in @("", "help", "-h", "--help") } {
        Show-Help
    }

    default {
        Write-Err "Unknown command: '$Command'"
        Show-Help
        exit 1
    }
}